name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool make gcc
    
    - name: Generate configure script
      run: |
        chmod +x autogen.sh
        ./autogen.sh
    
    - name: configure
      run: ./configure
    
    - name: make
      run: make
    
    - name: make check
      run: make check
    
    - name: make distcheck
      run: make distcheck